show databases;
show tables;

create database labexp1;
create table EMP (
		EMPNO NUMERIC (6),
        ENAME VARCHAR(20),
        JOB VARCHAR(10),
        MGR NUMERIC(4),
        DEPTNO NUMERIC(3), 
        SAL NUMERIC(7,2)
);

select  *from labexp1.emp;

alter table EMP modify ENAME varchar(20) not null;
alter table EMP modify JOB varchar(20) not null;

ALTER TABLE EMP ADD COMMISSION NUMERIC(20);

ALTER TABLE EMP MODIFY COLUMN JOB  VARCHAR(20);

CREATE TABLE DEPT (
	DEPTNO numeric(4) PRIMARY KEY,
    DEPTNAME varchar(10),
    LOC varchar(10)
 );

SELECT * FROM labexp1.DEPT;

ALTER TABLE EMP 
ADD FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO);

ALTER TABLE EMP 
ADD CONSTRAINT EMPNO CHECK (EMPNO > 100);

SELECT * FROM labexp1.EMP;

ALTER TABLE EMP
ALTER SAL SET DEFAULT 5000;

ALTER TABLE EMP ADD DOB DATE;

SELECT * FROM labexp1.EMP;

INSERT INTO DEPT (DEPTNO, DEPTNAME, LOC)
VALUES (1, "CA", "ORION" ),
(2, "MGNT", "TRINITY" ),
(3, "CSE", "NEO" );

SELECT * FROM labexp1.DEPT;

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, DEPTNO, SAL, COMMISSION, DOB)
VALUES (110, "AKSHAY", "SW ER", 12, 3, 300, 10, "2000-01-10" ),
(101, "ANAND", "SW ER", 12, 3, 200, 10, "2004-12-10" ),
(102, "BILL", "CEO", 0, 3, 1000, 20 , "2000-02-10" ),
(103, "BELL", "MANAGER", 17, 2, 100, 10, "2000-06-10" ),
(104, "CATHERINE", "MANAGER", 17, 2, 200, 10, "2000-11-10" ),
(105, "CARPIO", "MANAGER", 17, 2, 100, 10, "2001-01-10" ),
(106, "SHREYAS", "SW DEV", 19, 1, 500, 20, "2001-01-10" ),
(107, "SAM", "GEN MGR", 0, 2, 100, 20, "2002-01-10" ),
(108, "ELON", "RES ER", 19, 1, 5000, 50, "2005-01-10" ),
(109, "TESLA", "RES ER", 0, 1, 2000, 50, "2006-01-10" );

SELECT * FROM labexp1.EMP;

UPDATE EMP 
SET COMMISSION = 1000 WHERE  MGR = 0; 

SELECT * FROM labexp1.EMP;

CREATE TABLE EMP2 AS SELECT * FROM EMP;
SELECT * FROM labexp1.EMP2;

DELETE FROM EMP2
WHERE JOB = "MANAGER";
SELECT * FROM labexp1.EMP2;

DELETE FROM EMP2
WHERE EMPNO = 102;
SELECT * FROM labexp1.EMP2;

SELECT * FROM EMP 
ORDER BY SAL;

SELECT * FROM EMP 
ORDER BY SAL DESC;

SELECT * FROM EMP
WHERE DEPTNO = 3;

SELECT DISTINCT DEPTNO FROM EMP;

SELECT * FROM EMP 
ORDER BY ENAME ;

CREATE TABLE EMP3 AS SELECT * FROM EMP
WHERE JOB = "MANAGER";
SELECT * FROM labexp1.EMP3;

UPDATE EMP 
SET COMMISSION = 0 WHERE  EMPNO = 101 OR EMPNO = 105; 
SELECT * FROM labexp1.EMP;


SELECT ENAME FROM EMP
WHERE COMMISSION = 0;


SELECT * FROM EMP
WHERE COMMISSION = 0;



SELECT EMPNO, ENAME, DEPTNAME 
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;


CREATE TABLE EMP4 AS SELECT EMPNO, ENAME, DEPTNAME  
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM labexp1.EMP4;

SELECT EMPNO, ENAME, DOB FROM EMP;